In [19]:
from numpy import load
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

dict_data = load('/Users/apple/Desktop/graduate/Machine_Learning_Theory/MRI/npz/OAS1_0019_MR.npz')
data = dict_data['arr_0']

dict_data = load('/Users/apple/Desktop/graduate/Machine_Learning_Theory/MRI/npz/OAS1_0019_MRseg.npz')
data2 = dict_data['arr_0']


dict1_data = dict_data = load('/Users/apple/Desktop/graduate/Machine_Learning_Theory/MRI/OAS1_0019_MRskull_seg.npz')
data3 = dict1_data['arr_0']

dict2_data = dict_data = load('/Users/apple/Desktop/graduate/Machine_Learning_Theory/MRI/OAS1_0019_MRobs_seg.npz')
data4 = dict2_data['arr_0']

In [20]:
segment_ven = np.matrix(np.nonzero(data2 > 0))
segment_skull = np.matrix(np.nonzero(data3 > 0))
a = np.matrix(np.nonzero(data4 > 0))
segment_ven = segment_ven.T
segment_skull = segment_skull.T
print(a.T)
print(segment_skull)

[[ 20  72  11]
 [ 20  72  12]
 [ 20  73  11]
 ...
 [160  82  83]
 [160  83  83]
 [160  84  83]]
[[  0  32  43]
 [  0  32  44]
 [  0  32  45]
 ...
 [172 107  90]
 [172 107  91]
 [172 107  92]]


In [17]:
a.shape

(3, 366365)

In [18]:
segment_skull.shape

(366365, 3)